import sqlglot
from sqlglot.errors import ParseError

from GraphState import GraphState

# -----------------------------------
# Validate static SQL generated by LLM
# using sqlglot
# This catches hallucinations cheaply.
# -----------------------------------

def validate_static_sql(state: GraphState):
    sql = state["sql"]

    status = "Starting static validation (1 of 3)... "
    parsed = None
    try:
        parsed = sqlglot.parse_one(
            sql,
            dialect="snowflake"
        )
        print("SQL is valid")

    except ParseError as e:
        status = status + "\nFailed.\n"
        print("Invalid SQL:", e)

    status = status + "\nFinished static validation. \n"
    
    return {
        "validation_status": status,
        "parsed_sql": parsed
    }