import json
import sqlglot
from sqlglot import exp

from GraphState import GraphState

SEMANTIC_MODEL_PATH = "output/semantic_model.json"

# -----------------------------------
# Load semantic model
# -----------------------------------

with open(SEMANTIC_MODEL_PATH, "r") as f:
    semantic_model = json.load(f)


# -----------------------------------
# Validate semantic SQL generated by LLM
# using the semantic catalog provided
# Extremely important because
# Most text-to-SQL failures are semantic
# Checks:
# 1. table exists
# 2. column exists
# 3. joins allowed
# 4. metric references valid
# 5. grain compatibility
# 6. dimensions compatible with metric
# -----------------------------------

# ----------------------------------- 
# Build lookup structures
# -----------------------------------

def validate_semantic_sql(state: GraphState):

    parsed_sql = state["parsed_sql"]
    semantic_model = state["semantic_model"]
    models = semantic_model["models"]
    relationships = semantic_model.get("relationships", [])

    # output:
    validation_status = state["validation_status"] + "\nStarting semantic validation (2 of 3). \n"
    # -----------------------------------
    # Build lookup structures
    # -----------------------------------
    allowed_tables = set()
    table_columns = {}
    allowed_joins = set()

    for model in models:

        table_name = model["name"]

        allowed_tables.add(table_name)

        table_columns[table_name] = {
            col["name"]
            for col in model.get("columns", [])
        }

    for rel in relationships:

        allowed_joins.add(
            (
                rel["from_model"],
                rel["to_model"]
            )
        )

    # -----------------------------------
    # Validate tables
    # -----------------------------------

    tables_used = {}

    for table in parsed_sql.find_all(exp.Table):

        table_name = table.name
        alias = table.alias_or_name

        if table_name not in allowed_tables:
            validation_status += "ERROR table not found in catalog: " + table_name + '\n'
            raise Exception(
                f"Invalid table: {table_name}"
            )

        tables_used[alias] = table_name
        validation_status += "Found table in catalog: " + table_name + '\n'

    # -----------------------------------
    # Validate columns
    # -----------------------------------

    for column in parsed_sql.find_all(exp.Column):

        table_alias = column.table
        column_name = column.name

        if table_alias not in tables_used:
            continue

        real_table = tables_used[table_alias]

        if column_name not in table_columns[real_table]:
            validation_status += "ERROR column not found in catalog: " + column_name + '\n'
            raise Exception(
                f"""
                Invalid column:
                {real_table}.{column_name}
                """
            )
        
    validation_status += validation_status + "Found all columns in catalog. \n"

    # -----------------------------------
    # Validate joins
    # -----------------------------------

    for join in parsed_sql.find_all(exp.Join):

        joined_table = join.this.name

        join_condition = join.args.get("on")

        if not join_condition:
            continue

        columns = list(
            join_condition.find_all(exp.Column)
        )

        if len(columns) < 2:
            continue

        left_alias = columns[0].table
        right_alias = columns[1].table

        left_table = tables_used.get(left_alias)
        right_table = tables_used.get(right_alias)

        if not left_table or not right_table:
            continue

        valid = (
            (left_table, right_table) in allowed_joins
            or
            (right_table, left_table) in allowed_joins
        )

        if not valid:
            validation_status += f"""ERROR join not found in catalog: 
                {left_table} -> {right_table}
                \n"""
            raise Exception(
                f"""
                Invalid join:
                {left_table} -> {right_table}
                """
            )
        
    validation_status += validation_status + "Found all joins in catalog. \n"

    print("Semantic validation passed")

    return {
        "validation_status": validation_status,
    }