import json
import sqlglot
from sqlglot import expressions
from sqlglot import exp
from state import GraphState
from pathlib import Path
import importlib
from retrieval.semantic_data import models, relationships  # noqa: F401

# importlib.reload(json)
# -----------------------------------
# Validate semantic SQL generated by LLM
# using the semantic catalog provided
# Extremely important because
# Most text-to-SQL failures are semantic
# Checks:
# 1. table exists
# 2. column exists
# 3. joins allowed
# 4. metric references valid
# 5. grain compatibility
# 6. dimensions compatible with metric
# -----------------------------------

# -----------------------------------
# Build lookup structures
# -----------------------------------


def validate_semantic_sql(state: GraphState):

    parsed_sql_raw = state["parsed_sql"]
    if parsed_sql_raw is None or not isinstance(parsed_sql_raw, expressions.Select):
        raise Exception("Parsed SQL is not a valid SELECT statement.")

    parsed_sql: expressions.Select = parsed_sql_raw
    sql = state["sql"]
    # parsed_sql = sqlglot.parse_one(sql, dialect="snowflake")

    # output:
    validation_status = (
        state["validation_status"] + "\nStarting semantic validation (2 of 3). \n"
    )
    # -----------------------------------
    # Build lookup structures
    # -----------------------------------
    allowed_tables = set()
    table_columns = {}
    allowed_joins = set()

    # print("Processing model for semantic validation:", models)

    for model in models.values():
        table_name = model["name"]

        allowed_tables.add(table_name)

        table_columns[table_name] = {col["name"] for col in model.get("columns", [])}

    for rel in relationships:

        allowed_joins.add((rel["from_model"], rel["to_model"]))

    # -----------------------------------
    # Validate tables
    # -----------------------------------

    tables_used = {}

    for table in parsed_sql.find_all(exp.Table):

        table_name = table.name
        alias = table.alias_or_name

        if table_name not in allowed_tables:
            validation_status += (
                "ERROR table not found in catalog: " + table_name + "\n"
            )
            error = f"Invalid table: {table_name}"
            print("Semantic Validation:", error)
            raise Exception(error)

        tables_used[alias] = table_name
        validation_status += "Found table in catalog: " + table_name + "\n"

    # -----------------------------------
    # Validate columns
    # -----------------------------------

    for column in parsed_sql.find_all(exp.Column):

        table_alias = column.table
        column_name = column.name

        if table_alias not in tables_used:
            continue

        real_table = tables_used[table_alias]

        if column_name not in table_columns[real_table]:
            validation_status += (
                "ERROR column not found in catalog: " + column_name + "\n"
            )
            error = f"Invalid column: {real_table}.{column_name}"
            print("Semantic Validation:", error)
            raise Exception(error)

    validation_status += validation_status + "Found all columns in catalog. \n"

    # -----------------------------------
    # Validate joins
    # -----------------------------------

    for join in parsed_sql.find_all(exp.Join):

        joined_table = join.this.name

        join_condition = join.args.get("on")

        if not join_condition:
            continue

        columns = list(join_condition.find_all(exp.Column))

        if len(columns) < 2:
            continue

        left_alias = columns[0].table
        right_alias = columns[1].table

        left_table = tables_used.get(left_alias)
        right_table = tables_used.get(right_alias)

        if not left_table or not right_table:
            continue

        valid = (left_table, right_table) in allowed_joins or (
            right_table,
            left_table,
        ) in allowed_joins

        if not valid:
            validation_status += f"""ERROR join not found in catalog: 
                {left_table} -> {right_table}
                \n"""
            error = f"""Invalid join:
                {left_table} -> {right_table}
                """
            print("Semantic Validation:", error)
            raise Exception(error)

    validation_status += validation_status + "Found all joins in catalog. \n"

    print("Semantic Validation: passed")

    return {
        "validation_status": validation_status,
    }
