import sqlglot
from sqlglot.errors import ParseError
from state import GraphState

# -----------------------------------
# Validate static SQL generated by LLM
# using sqlglot
# This catches hallucinations cheaply.
# -----------------------------------


def validate_static_sql(state: GraphState):
    sql = state["sql"]

    status = "Starting static validation (1 of 3)... "

    try:
        parsed = sqlglot.parse_one(sql, dialect="snowflake")
        print("Static Validation: SQL is valid")

    except ParseError as e:
        status = status + "\nFailed.\n"
        print("Static Validation: Invalid SQL:", e)

    status = status + "\nFinished static validation. \n"

    return {"validation_status": status, "parsed_sql": parsed}
